### PR TITLE
Issue 425: added check for audio playing before trying to record

### LINKED ISSUE #425: SR and TTS interfere with each other
**Describe the bug**
When both TTS and SR are active at the same time according to my RA, the SR hears itself reading and glitches.

**To Reproduce**
Please confirm. If confirmed, place a check so that when TTS is speaking the SR microphone is turned off. SR should not be available during any reading.

### PR DESCRIPTION
**Pull request by JRustyHaner**
fixes #425

### CODE REVIEW

File: mofacts/client/views/experiment/card.js [hunk 1]
```diff
@@ -2147,10 +2147,12 @@ function speakMessageIfAudioPromptFeedbackEnabled(msg, audioPromptSource) {
           audioPromptSpeakingRate = Session.get('audioPromptQuestionSpeakingRate');
           audioPromptVolume = Session.get('audioPromptQuestionVolume')
         }
+
         makeGoogleTTSApiCall(msg, ttsAPIKey, audioPromptSpeakingRate, audioPromptVolume, function(audioObj) {
           if (window.currentAudioObj) {
             window.currentAudioObj.pause();
           }
+          Session.set('audioObject'.audioObj)
```
Comment (MegaGeese) [inline mofacts/client/views/experiment/card.js:2155]: I think you meant to put a comma here

**Review by MegaGeese — CHANGES_REQUESTED** [review]

**Review by MegaGeese — CHANGES_REQUESTED** [review]
SR is still hearing the TTS. Also if the user says nothing the system enters an infinite loop
