### PR TITLE
Issue 363: Teacher progress reports not displaying classname

### LINKED ISSUE #363: Progress report doesn't appear for instructor reporting button
**Describe the bug**
Test class wasn't in dropdown

### PR DESCRIPTION
**Pull request by JRustyHaner**
fixes #363

### CODE REVIEW

File: mofacts/client/views/experimentReporting/instructorReporting.js [hunk 1]
```diff
@@ -170,6 +170,7 @@ Template.instructorReporting.onRendered(async function() {
   Session.set('studentPerformanceForClassAndTdfIdMap', studentPerformanceForClassAndTdfIdMap);
 
   const instructorReportingTdfs = await meteorCallAsync('getTdfAssignmentsByCourseIdMap', Meteor.userId());
+  console.log('rusty', instructorReportingTdfs);
```
Comment (MegaGeese) [inline mofacts/client/views/experimentReporting/instructorReporting.js:173]: 'rusty'

**Review by MegaGeese — CHANGES_REQUESTED** [review]
