### PR TITLE
Iss561: Add delete buttons as a temporary fix for #556

### LINKED ISSUE #561: Add delete button for content
Admins should be able to delete TDFs and Stims they own

### PR DESCRIPTION
**Pull request by JRustyHaner**
Fixes #561

### CODE REVIEW

File: mofacts/server/methods.js [hunk 1]
```diff
@@ -2139,6 +2134,34 @@ Meteor.startup(async function() {
...
 
+    //handle file deletions
+    deleteStimFile: async function(stimFilename) {
+      console.log('delete Stim File', stimFilename);
+      const query = 'DELETE FROM item WHERE stimulusFilename = $1';
+      await db.none(query, [stimFilename]);
+      const query2 = 'SELECT stimuliSetId FROM item WHERE stimulusFilename = $1 LIMIT 1';
+      await db.none(query2, [stimFilename]);
+      res = "Stim deleted.";
+      return res;
```
Comment (MegaGeese) [inline mofacts/server/methods.js:2145]: We can have stim files without tdfs but we cannot have tdfs without stim files. When a user deletes a stim is should also delete all related tdfs

**Review by MegaGeese — CHANGES_REQUESTED** [review]
