### PR TITLE
Iss267: Item removal by student

### LINKED ISSUE #267: Item removal by student
A button that appears during review, in the bottom right corner. With a feedback popup if student uses it. 

Button text "Report this item as wrong and remove it."

Feedback popup "Thanks, we’ll take it out of your stack." (with continue button)

Student presses button, no outcome will be recorded for the trial (e.g. mark it “Removal” in outcome column for the trial in data output)

Special flag is set for stimuli in the componentstate table (model code will be fed this info and always compute the item p=0, preventing its selection for that student and allowing us to quickly search for these items so as to not include them in the progress gauges (do count past time and percent correct for the items, but not the other 3 readouts...)

### PR DESCRIPTION
**Pull request by MegaGeese**
Allows the user to mark a question as incorrect.
Added a column to the componentState table for if a stimulus is to be shown.
Modified the history table to show 'removal' as an outcome for stimuli that the user removed. 

Removal button will not be shown if there are less than 3 remaining stimuli. 

Closes #267

### CODE REVIEW

**Review by andrewtackett — CHANGES_REQUESTED** [review]
This was a large feature and I want to stress that overall you did quite well implementing it despite my many feedback comments.  Good job.

File: mofacts/client/lib/sessionUtils.js [hunk 1]
```diff
@@ -61,6 +61,7 @@ function sessionCleanUp() {
 
   Session.set('isReport', false);
   Session.set('hiddenItems', []);
+  Session.set('numVisableCards', 0);
```
Comment (andrewtackett) [inline mofacts/client/lib/sessionUtils.js:64]: Misspelled visible :P

File: mofacts/server/methods.js [hunk 2]
```diff
@@ -713,19 +713,15 @@ async function setExperimentState(UserId, TDFId, newExperimentState) { // by cur
   return TDFId;
 }
 
-async function insertHiddenItem(userId, clusterKC) {
-  let query = 'UPDATE componentstate SET showitem = FALSE WHERE userid = $1 AND kcid = $2';
-  await db.manyOrNone(query, [userId, clusterKC]);
+async function insertHiddenItem(userId, stimulusKC, tdfId) {
+  let query = 'UPDATE componentstate SET showitem = FALSE WHERE userid = $1  AND tdfid = $2 AND kcid = $3 AND componenttype = \'stimulus\'';
```
Comment (andrewtackett) [inline mofacts/server/methods.js:717]: Prefer to do double quotes when inside single quotes instead of escaping

File: mofacts/server/methods.js [hunk 3]
```diff
@@ -713,19 +713,15 @@ async function setExperimentState(UserId, TDFId, newExperimentState) { // by cur
...
+  await db.manyOrNone(query, [userId, tdfId, stimulusKC]);
 }
 
 async function getHiddenItems(userId, tdfId) {
-  let query = 'SELECT kcid FROM componentstate WHERE userid = $1 AND tdfid = $2 AND showitem = false';
+  let query = 'SELECT kcid FROM componentstate WHERE userid = $1 AND tdfid = $2 AND showitem = false AND componenttype = \'stimulus\'';
```
Comment (andrewtackett) [inline mofacts/server/methods.js:722]: Same as above

**Review by andrewtackett — CHANGES_REQUESTED** [review]
Looks pretty good generally, have you tested and verified it works in learning sessions and doesn't break assessment sessions?

File: mofacts/server/methods.js (hunk 2 above)
Comment (MegaGeese) [reply mofacts/server/methods.js]: Turns out to do this you have to put the whole query in double quotes and then the string parameter in single quotes.

File: mofacts/client/views/experiment/unitEngine.js [hunk 4]
```diff
@@ -1039,7 +1037,14 @@ function modelUnitEngine() {
           });
         }
       }
-      Session.set('numVisableCards', numVisableCards - hiddenItems.length);
+
+      let numVisibleCards = 0;
+      for (let i = 0; i < cardProbabilities.cards.length; i++){
+        if(cardProbabilities.cards[i].canUse){
```
Comment (andrewtackett) [inline mofacts/client/views/experiment/unitEngine.js:1043]: i thought you were using the kc num to identify hidden/visible cards?

File: mofacts/client/lib/sessionUtils.js [hunk 5]
```diff
@@ -59,6 +59,10 @@ function sessionCleanUp() {
 
   Session.set('schedule', undefined);
 
+  Session.set('isReport', false);
+  Session.set('hiddenItems', []);
+  Session.set('numVisibleCards', 0);
```
Comment (andrewtackett) [inline mofacts/client/lib/sessionUtils.js:64]: this is good but we still shouldn't rely on operational ordering to happen to initialize this by side-effect.  can you set this in card.js as well? outside of functions near the top, as putting it in rendered is after we would need it to be initialized

File: mofacts/client/views/experiment/card.js [hunk 6]
```diff
@@ -2689,6 +2707,28 @@ async function checkSyllableCacheForCurrentStimFile(cb) {
...
+  let clusterIndex = Session.get('clusterIndex');
+  let stims = getStimCluster(clusterIndex).stims; 
+  let whichStim = engine.findCurrentCardInfo().whichStim;
+  const userId = Meteor.userId();
+  const tdfId = Session.get('currentTdfId');
+
+  await meteorCallAsync('insertHiddenItem', userId, stims[whichStim].stimulusKC);
+  Session.set('hiddenItems', await meteorCallAsync('getHiddenItems', userId, tdfId));
+  Session.set('numRemainingCards', await engine.getCardCount());
+  Session.set('isReport', true);
```
[the remark this answers is not in the document]
Comment (andrewtackett) [reply mofacts/client/views/experiment/card.js]: @MegaGeese I think you missed fixing some of this one

File: mofacts/server/methods.js [hunk 7]
```diff
@@ -713,6 +713,21 @@ async function setExperimentState(UserId, TDFId, newExperimentState) { // by cur
...
+}
+
+async function getHiddenItems(userId, tdfId) {
+  let query = 'SELECT kcid FROM componentstate WHERE userid = $1 AND tdfid = $2 AND showitem = false';
+  const hiddenItems = await db.manyOrNone(query, [userId, tdfId]);
+  let ret = [];
+  for(let i = 0; i < hiddenItems.length; i++){
+    ret.push(hiddenItems[i].kcid);
+  }
+  return [...new Set(ret)];
```
[the remark this answers is not in the document]
Comment (andrewtackett) [reply mofacts/server/methods.js]: @MegaGeese Seems like you deleted the deduplication here in the new version?

**Review by andrewtackett — CHANGES_REQUESTED** [review]
nearly there

File: mofacts/client/views/experiment/unitEngine.js (hunk 4 above)
Comment (MegaGeese) [reply mofacts/client/views/experiment/unitEngine.js:1043]: This is used to find the total number of cards that were visable to the user through the <clusterlist> tag in the tdf file. If a cluster is being used by the tdf then the canUse parameter is set to true. This is just to get the total number of stims enabled in the tdf. Afterwards the number of hidden items is subtracted from the total.

Comment (andrewtackett) [reply mofacts/client/views/experiment/unitEngine.js:1043]: Ah, carry on then

File: mofacts/client/views/experiment/card.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (MegaGeese) [reply mofacts/client/views/experiment/card.js]: I've updated this to only send data to the db through "insertHiddenItems". hiddenItems and numVisibleCards gets set client side without the db call now.

File: mofacts/server/methods.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (MegaGeese) [reply mofacts/server/methods.js]: Yes. Since the new query specifications limit the returned hiddenItems to a unique set of stimulus KC IDs. So there would be no point in going from a set to an array.

**Review by andrewtackett — CHANGES_REQUESTED** [review]
A few minor things

**Review by andrewtackett — APPROVED** [review]
