### PR TITLE
Issue 455: Refutation not working

### LINKED ISSUE #455: Refutation not working
**Describe the bug**
Not working

mofacts_app and 14 more pages - Personal - Microsoft​ Edge 12_5_2021 3_56_16 PM
mofacts_app and 14 more pages - Personal - Microsoft​ Edge 12_5_2021 3_56_11 PM

**To Reproduce**
Run posted tdf

**Expected behavior**
e.

### PR DESCRIPTION
**Pull request by MegaGeese**
Refutation now works. System will try to load from elaborated feedback cache first and then the glossary second. 

There is a bug with the countdown timer causing refutational feedback to disappear during the countdown. Disabling that feature until issue is resolved. 

closes #455

### CODE REVIEW

File: mofacts/server/lib/CachedElaboratedFeedback.js [hunk 1]
```diff
@@ -115,7 +117,7 @@ function GenerateFeedback(incorrectAnswer$$1, correctAnswer$$1) {
       const ef = matchValue[0];
       elaboratedFeedback = ef;
     }
-
+
```
Comment (JRustyHaner) [inline mofacts/server/lib/CachedElaboratedFeedback.js:120]: Additional space here
