### PR TITLE
Issue 380: Get rid of intersitials when not needed

### LINKED ISSUE #380: Unneeded interface actions
**Describe the bug**
Flashing of the interface due to unnecessary rendering on instructions when they will be blank. (Rusty this is one you mentioned)

**Expected behavior**
No rendering that is unneeded

### PR DESCRIPTION
**Pull request by JRustyHaner**
Closes #380

### CODE REVIEW

File: mofacts/client/views/experiment/card.js [hunk 1]
```diff
@@ -2890,9 +2890,11 @@ async function processUserTimesLog() {
     // Initialize client side student performance
     const curUser = Meteor.user();
     const currentTdfId = Session.get('currentTdfId');
+    const curTdf = Session.get('currentTdfFile');
+    const curTdfUnit = curTdf.tdfs.tutor.unit[0];
     await setStudentPerformance(curUser._id, curUser.username, currentTdfId);
 
-    if (needFirstUnitInstructions) {
+    if (needFirstUnitInstructions && (curTdfUnit.unitinstructions != "" || typeof curTdfUnit.unitinstructions !== 'undefined')) {
```
Comment (MegaGeese) [inline mofacts/client/views/experiment/card.js:2897]: something cannot be equal to both "" and undefined. This logic will always return true.

**Review by MegaGeese — CHANGES_REQUESTED** [review]

File: mofacts/client/views/experiment/card.js [hunk 2]
```diff
@@ -2909,7 +2911,7 @@ async function processUserTimesLog() {
         if (lockoutMins > 0) {
           const unitStartTimestamp = Session.get('currentUnitStartTime');
           const lockoutFreeTime = unitStartTimestamp + (lockoutMins * (60 * 1000)); // minutes to ms
-          if (Date.now() < lockoutFreeTime) {
+          if (Date.now() < lockoutFreeTime && (typeof curTdfUnit.unitinstructions !== 'undefined') {
```
Comment (MegaGeese) [inline mofacts/client/views/experiment/card.js:2914]: Missing a `)` here causing a compilation error.

File: mofacts/client/views/experiment/card.js [hunk 3]
```diff
@@ -1775,7 +1775,7 @@ async function unitIsFinished(reason) {
   Session.set('curUnitInstructionsSeen', false);
 
   let leaveTarget;
-  if (newUnitNum < curTdf.tdfs.tutor.unit.length) {
+  if (newUnitNum < curTdf.tdfs.tutor.unit.length && typeof curTdfUnit.unitinstructions !== 'undefined'){
```
Comment (MegaGeese) [inline mofacts/client/views/experiment/card.js:1778]: This looks to be having an unintended effect where it will kick the user out of the session in-between units

**Review by MegaGeese — CHANGES_REQUESTED** [review]
